name: Pull Request Validation

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  a-simple-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Run lint
        run: npm run lint
      - name: CDK Synth
        run: npm run cdk:synth
